theme: minima
title: BBS Motorsports Hardware Info
description: Information on BBS Motorsports Hardware

minima:
  skin: dark

header_pages:
 - wheel-halves/16-inch-wheels.md
 - wheel-halves/17-inch-wheels.md
 - wheel-halves/18-inch-wheels.md
 - wheel-centers.md
 - wheel-accessories.md
