theme: minima
title: BBS Motorsports Hardware Info
description: Information on BBS Motorsports Hardware

minima:
  skin: dark

header_pages:
 - 16-inch-wheels.md
 - 17-inch-wheels.md
 - 18-inch-wheels.md
 - wheel-centers.md
 - wheel-accessories.md
